name: tokenized-strategy-ape-mix

plugins:
  - name: solidity
  - name: etherscan
  - name: hardhat
  - name: infura
  - name: alchemy
  - name: foundry
  - name: ens

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.9.5
  - name: yearn
    github: yearn/yearn-vaults
    version: 0.4.6

solidity:
  import_remapping:
    - "@openzeppelin/contracts@4.9.5=openzeppelin/v4.9.5"
    - "@openzeppelin/contracts=openzeppelin/v4.9.5"
    - "github.com/yearn/yearn-vaults/blob/v0.4.6=yearn/v0.4.6"

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: foundry
    transaction_acceptance_timeout: 600 # 5 minutes

hardhat:
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy

foundry:
  priority_fee: 0
  base_fee: 0
  gas_price: 0
  fork:
    ethereum:
      mainnet:
        upstream_provider: alchemy
